### PR TITLE
Update manual to include BATS

### PR DESCRIPTION
**Pull request by jhkennedy**
@matthewhoffman, @stephenprice and @whlipscomb, please review. 

In ACME-Climate/cism-piscees#40, a number of files were renamed, and the
build and test structre (BATS) was added to CISM.

This commit updates the users manual to reflect these changes, and now
includes a section (8.3) in the Test Cases chapter which discusses BATS.

---

I'm not sure how involved to get describing BATS in the users manual, or if this is the best place for it to go. So, let me know if you want me to make any changes.

### CODE REVIEW

**Comment by matthewhoffman** [comment]
@jhkennedy , this looks great.  Thanks a lot for taking the time to update the documentation with these changes.  I think the BATS description you added is good.  We can always expand it later, but it's nice to have at least some details explaining what this new directory is and how to use it.

Once we complete the merge of the code to master and tag a release, we should get an updated version of the documentation onto the website (I can do that).  We should update the version number on the title page of the documentation to be 2.0.5 (if I remember where that gets controlled.  It looks like it's controlled by \glimmerver.  I think that is set manually somewhere in the documentation repo.  If you can find that, feel free to update it with a new commit to this branch).

**Comment by jhkennedy** [comment]
@matthewhoffman, of course! 

I just bumped the version number to 2.0.5 (it's in `common/version.tex`). 

I added myself to the developers list, but should I also add myself to the authors list for the Manual?

**Comment by matthewhoffman** [comment]
Yeah, go for it.

**Comment by jhkennedy** [comment]
@matthewhoffman , @stephenprice , @whlipscomb  -- I just check this over, and it is still up to data with the changes in ACME-Climate/cism-piscees#40.

**Comment by matthewhoffman** [comment]
@jhkennedy , thanks for updating this too.  I've merged it and updated the online documentation pdf at http://oceans11.lanl.gov/cism/data/cism_documentation_v2.0.pdf.

**Comment by stephenprice** [comment]
@jhkennedy , @matthewhoffman , thanks for pushing this out, including the documentation updates. One question regarding that, is there somewhere in the updated documentation where we discuss LIVV, in case people want to know about / use that? I don't think that would have to be exhaustive, but it might be worth a sentence or two and a link to the github repo?

**Comment by jhkennedy** [comment]
@matthewhoffman , great! 

@stephenprice , the CISM manual discusses how to use BATS briefly and refers people to the README. The CISM manual states BATS is intended to be used with LIVVkit (with link to it on github) and that the LIVVkit+BATS workflow documentation is maintained on the LIVVkit wiki (with a link to the wiki). Additionally, the README goes into a bit more detail, and also provides links to various LIVVkit wiki pages. 

I think that should cover anyone wanting to check LIVVkit out -- they are bound to run across a link. :smile:

**Comment by stephenprice** [comment]
@jhkennedy , sounds great Joe. Thanks for being so thorough.

**Pull request merged**
