### PR TITLE
Fixed a couple of typos where .pdd should be .smb

### PR DESCRIPTION
**Pull request by jhkennedy**
@stephenprice I noticed a couple of small typos. I figured this would be easiest.

### CODE REVIEW

**Comment by whlipscomb** [comment]
Hi Joe,
Thanks for catching these typos.  One small thing: I noticed that you revised both line 184 and line 186 of the file shallow-ice-model-tests.tex. The 'pdd' suffixes in the old version of l. 184 are correct; only l. 186 should be changed.

Bill

**Comment by jhkennedy** [comment]
Hi @whlipscomb,

You're right, L184 should not have changed. I changed it back. 

I also changed the first .pdd on L186 to .smb. <-- the change I thought I was making last commit. 

Sorry!
Joe

**Comment by whlipscomb** [comment]
Great—thanks!

On Jan 23, 2015, at 12:07 PM, Joseph H Kennedy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @whlipscombhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_whlipscomb&d=AwMCaQ&c=KZJWt40Ec3xgv0ORfhSJcvXZuqMxUG5r9f2nGq4AjVA&r=oxCcN5DkMbF8-WlcbLXtKJ-cCBOu2usTEMHDq5PdzV4&m=XDfz2N7-g6vATXNzelpZvVCQ4_Vfb1WtRXOIck2A2mY&s=iG27Tdy5lW1m5D0lWyABmV6fnceVofXXw8CrIoVGzS4&e=,

You're right, L184 should not have changed. I changed it back.

I also changed the first .pdd on L186 to .smb. <-- the change I thought I was making last commit.

Sorry!
Joe

—
Reply to this email directly or view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CISM_cism-2Ddocumentation_pull_1-23issuecomment-2D71246734&d=AwMCaQ&c=KZJWt40Ec3xgv0ORfhSJcvXZuqMxUG5r9f2nGq4AjVA&r=oxCcN5DkMbF8-WlcbLXtKJ-cCBOu2usTEMHDq5PdzV4&m=XDfz2N7-g6vATXNzelpZvVCQ4_Vfb1WtRXOIck2A2mY&s=n-YJqF1c8kFkSsLI4KQC0uTuPF7S4ABeXCmFR3PUqoI&e=.

---

William Lipscomb
Los Alamos National Laboratory
Group T-3, MS B216
Los Alamos, NM 87545
505-667-0395

**Comment by matthewhoffman** [comment]
Thanks @jhkennedy!  I've merged your branch and updated the PDF at http://oceans11.lanl.gov/cism/documentation.html.

**Pull request merged**
